### ISSUE TITLE
use code in another project

### ISSUE THREAD

**Issue by snowbabyjia** [mcuadros/bson-hni#2]
Hi Maximo,
I'm developing the mongo-hhvm-driver project https://github.com/10gen-labs/mongo-hhvm-driver and particularly on the encoding from hhvm/php to bson. I saw your work in this directory, and found that your encode.h, encode.cpp and class.h files are very useful for our project. So I'm wondering if I could use the above mentioned files in our project. Of course we would clearly state that the files are from you in appropriate ways (create a contrib directory, clearly state this in README etc). Please let me know, and thank you very much!!

**Comment by mcuadros** [comment]
Hi,

@snowbabyjia if you wish i can make a pr or feel free to use it.

/cc @jmikola

**Comment by jmikola** [comment]
Thanks, @mcuadros. I advised keeping most of the code in one file (under `contrib/`) with your license in the header.

**Comment by mcuadros** [comment]
Ok, then go ahead. :D
